export const EVENT = {
    LOAD: "REQUEST_EVENT_DATA",
    LOAD_SUCCESS: "FETCH_EVENT_DATA_SUCCESS",
    LOAD_FAIL: "FETCH_EVENT_DATA_FAIL"
}
export const CLASSES = {
    LOAD : "REQUEST_CLASSES_DATA",
    LOAD_SUCCESS :  "FETCH_CLASSES_DATA_SUCCESS"
}